name: 7DaysToMine
version: '1.0'
main: com.github.yukkimoru.sdtm.SDTM
api-version: '1.21'
authors: [ YukkiMoru ]
website: https://github.com/YukkiMoru

commands:
  sd:
    description: A command for 7DaysToMine plugin
    usage: /<command>